version: '3.7'
services:
  ##############
  ## POSTGRES ##
  postgres:
    env_file:
      - .env
    image: postgres
    networks:
      - db
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: always
#    Если нужно сохранять бд при перестройке контейнеров
#    volumes:
#      - ./_volume/postgres:/var/lib/postgresql/data
    container_name: postgres
  ################
  ## PG ADMINER ##
  pgadmin4:
      env_file:
        - .env
      image: dpage/pgadmin4
      networks:
        - db
      ports:
        - ${PGADMIN_PORT}:80
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        PGADMIN_CONFIG_SERVER_MODE: ${PGADMIN_CONFIG_SERVER_MODE}
      restart: unless-stopped
#      volumes:
#        - ./_volume/pgadmin:/var/lib/pgadmin
      container_name: pgadmin4

networks:
  db:
    driver: bridge